#!/usr/bin/env bun
/**
 * Upgrade migration for v0.6.0 — the home focus page moves into the dashboard.
 *
 * Before: `focus_write` rendered `<HOME>/focus.html` for all work. After: the
 * dashboard's Today → Focus tab is that view, and only projects keep a focus
 * page. The old page is generated output, so it is removed, but only when it
 * carries the `focus-data` block every generated page embeds; a hand-made file
 * at the same path is left alone and reported.
 *
 * Run by `/agent-kevin:upgrade` via `run_upgrade` (outside the Bash sandbox).
 * Idempotent. Contract: prints a single-line JSON report as its LAST stdout
 * line; exits non-zero on failure.
 */
import { existsSync, readFileSync, rmSync } from 'node:fs';
import { resolve } from 'node:path';

const VERSION = '0.6.0';
const first = (...values: (string | undefined)[]): string | undefined =>
  values.map((value) => value?.trim()).find((value) => value);

const HOME = resolve(first(process.env.KEVIN_HOME, process.env.AGENT_HOME) ?? process.cwd());
const FOCUS_PAGE = resolve(HOME, 'focus.html');
const FOCUS_DATA = /<script\s+type="application\/json"\s+id="focus-data"\s*>/;

type Action = 'removed' | 'kept-hand-made' | 'absent';

interface Report {
  ok: true;
  version: string;
  action: Action;
  notes: string[];
}

const migrate = (): Report => {
  if (!existsSync(FOCUS_PAGE)) {
    return { ok: true, version: VERSION, action: 'absent', notes: [] };
  }
  if (!FOCUS_DATA.test(readFileSync(FOCUS_PAGE, 'utf-8'))) {
    return {
      ok: true,
      version: VERSION,
      action: 'kept-hand-made',
      notes: [
        'focus.html has no focus-data block, so it was not generated by focus_write and was left in place. The home focus view now lives in the dashboard (Today → Focus).'
      ]
    };
  }
  rmSync(FOCUS_PAGE);
  return {
    ok: true,
    version: VERSION,
    action: 'removed',
    notes: ['The home focus view now lives in the dashboard (Today → Focus); project focus pages are unchanged.']
  };
};

try {
  process.stdout.write(JSON.stringify(migrate()) + '\n');
} catch (err) {
  const message = err instanceof Error ? err.message : String(err);
  process.stdout.write(JSON.stringify({ ok: false, version: VERSION, error: message }) + '\n');
  process.exit(1);
}
