import { afterAll, describe, expect, test } from 'bun:test';
import { spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, symlinkSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

const SCRIPT = resolve(import.meta.dir, '0.6.1.ts');

const OLD_TASKS = `> Tasks hub — auto-generated by Kevin from task frontmatter on every mutation.

<!-- GOALS:START -->
## Weekly Goals

_No weekly goals set yet — run the weekly-goals skill to set them._

## Monthly Goals

_No monthly goals set yet — run the monthly-goals skill (Ace proposes on the 1st of each Hijri month)._

## Yearly Goals

- **Q4** — Ship the acme portal _(check: live for two tenants)_
<!-- GOALS:END -->

## Active (0)
`;

const homes: string[] = [];
const makeHome = (files: Record<string, string> = {}): string => {
  const home = mkdtempSync(join(tmpdir(), 'migrate-061-'));
  homes.push(home);
  Object.entries(files).forEach(([rel, content]) => {
    mkdirSync(resolve(home, rel, '..'), { recursive: true });
    writeFileSync(join(home, rel), content);
  });
  return home;
};
const run = (home: string): Record<string, unknown> => {
  const env = Object.fromEntries(Object.entries(process.env).filter(([key]) => !/^(KEVIN|AGENT)_/.test(key))) as Record<
    string,
    string
  >;
  const result = spawnSync('bun', [SCRIPT], {
    env: { ...env, KEVIN_HOME: home, AGENT_HOME: home },
    encoding: 'utf-8'
  });
  expect(result.status).toBe(0);
  return JSON.parse(result.stdout.trim().split('\n').at(-1) ?? '{}');
};
const readJsonFile = (path: string): unknown => JSON.parse(readFileSync(path, 'utf-8'));

afterAll(() => homes.forEach((home) => rmSync(home, { recursive: true, force: true })));

describe('0.6.1 skill consolidation', () => {
  test('maps retired grants to their successors in place, keeps the stricter placement, then is a no-op', () => {
    const home = makeHome({
      '.claude/settings.json': JSON.stringify({
        permissions: {
          allow: [
            'Read',
            'Skill(agent-kevin:seed-export)',
            'Skill(agent-kevin:focus)',
            'Skill(agent-kevin:quick-pulse)',
            'Skill(other:seed-export)'
          ],
          ask: ['Skill(agent-kevin:seed-import)', 'Bash(git push*)'],
          deny: ['Skill(agent-kevin:google-page-speed)']
        },
        theme: 'dark'
      })
    });
    expect(run(home)).toMatchObject({
      ok: true,
      grants: [
        { list: 'deny', from: 'Skill(agent-kevin:google-page-speed)', to: 'Skill(agent-kevin:seo)' },
        { list: 'ask', from: 'Skill(agent-kevin:seed-import)', to: 'Skill(agent-kevin:seed)' },
        { list: 'allow', from: 'Skill(agent-kevin:seed-export)', to: 'Skill(agent-kevin:seed)' },
        { list: 'allow', from: 'Skill(agent-kevin:quick-pulse)', to: 'Skill(agent-kevin:briefing)' }
      ],
      notes: [expect.stringContaining('google-page-speed'), expect.stringContaining('seed-import')]
    });
    expect(readJsonFile(join(home, '.claude/settings.json'))).toEqual({
      permissions: {
        allow: ['Read', 'Skill(agent-kevin:focus)', 'Skill(agent-kevin:briefing)', 'Skill(other:seed-export)'],
        ask: ['Skill(agent-kevin:seed)', 'Bash(git push*)'],
        deny: ['Skill(agent-kevin:seo)']
      },
      theme: 'dark'
    });
    expect(run(home)).toMatchObject({ ok: true, grants: [], notes: [] });
  });

  test('migrates settings.local.json too, keeping its indentation, wildcards and entries it does not own', () => {
    const local = JSON.stringify(
      {
        env: { GSC_SITE_URL: 'https://acme.example/' },
        permissions: { allow: ['Bash(ls *)', 42, 'Bash(ls *)', 'Skill(agent-kevin:quick-pulse *)'], deny: ['Read'] }
      },
      null,
      4
    );
    const home = makeHome({ '.claude/settings.local.json': local });
    expect(run(home)).toMatchObject({
      grants: [
        {
          file: join('.claude', 'settings.local.json'),
          list: 'allow',
          from: 'Skill(agent-kevin:quick-pulse *)',
          to: 'Skill(agent-kevin:briefing *)'
        }
      ]
    });
    expect(readFileSync(join(home, '.claude/settings.local.json'), 'utf-8')).toBe(
      local.replace('Skill(agent-kevin:quick-pulse *)', 'Skill(agent-kevin:briefing *)')
    );
  });

  test('moves cadence keys, the later date winning either way', () => {
    const home = makeHome({
      '.kevin/cadence.json': JSON.stringify({
        'weekly-goals': '2026-09-21',
        'goals-week': '2026-09-28',
        'monthly-goals': '2026-09-01',
        'goals-month': '2026-08-01',
        'yearly-goals': '2026-07-26',
        custom: '2026-01-01'
      })
    });
    expect(run(home)).toMatchObject({
      cadence: [
        { from: 'weekly-goals', to: 'goals-week' },
        { from: 'monthly-goals', to: 'goals-month' },
        { from: 'yearly-goals', to: 'goals-year' }
      ]
    });
    expect(readJsonFile(join(home, '.kevin/cadence.json'))).toEqual({
      custom: '2026-01-01',
      'goals-week': '2026-09-28',
      'goals-month': '2026-09-01',
      'goals-year': '2026-07-26'
    });
    expect(run(home)).toMatchObject({ cadence: [] });
  });

  test('an unreadable cadence file is noted, not fatal', () => {
    const home = makeHome({ '.kevin/cadence.json': '{"weekly-goals": ' });
    expect(run(home)).toMatchObject({ ok: true, cadence: [], notes: [expect.stringContaining('cadence.json')] });
  });

  test('rewords every old goal placeholder and adds Daily Goals, leaving set goals alone', () => {
    const home = makeHome({ 'projects/TASKS.md': OLD_TASKS });
    expect(run(home)).toMatchObject({ tasks: 'updated' });
    const tasks = readFileSync(join(home, 'projects/TASKS.md'), 'utf-8');
    expect(tasks).toContain(
      "<!-- GOALS:START -->\n## Daily Goals\n\n_No daily goals set yet — run `goals day` to set today's._\n\n## Weekly Goals\n\n_No weekly goals set yet — run `goals week` to set them._"
    );
    expect(tasks).toContain('_No monthly goals set yet — run `goals month`._');
    expect(tasks).toContain('- **Q4** — Ship the acme portal _(check: live for two tenants)_');
    expect(tasks).not.toContain('-goals skill');
    expect(tasks.endsWith('<!-- GOALS:END -->\n\n## Active (0)\n')).toBe(true);
    expect(run(home)).toMatchObject({ tasks: 'unchanged' });
  });

  test('keeps CRLF line endings in TASKS.md', () => {
    const home = makeHome({ 'projects/TASKS.md': OLD_TASKS.replaceAll('\n', '\r\n') });
    expect(run(home)).toMatchObject({ tasks: 'updated' });
    const tasks = readFileSync(join(home, 'projects/TASKS.md'), 'utf-8');
    expect(tasks.replaceAll('\r\n', '')).not.toContain('\n');
    expect(tasks).toContain('<!-- GOALS:START -->\r\n## Daily Goals\r\n\r\n');
  });

  test('a TASKS.md without the goals markers is left alone', () => {
    const home = makeHome({ 'projects/TASKS.md': '# Tasks\n' });
    expect(run(home)).toMatchObject({ tasks: 'no-goals-block' });
    expect(readFileSync(join(home, 'projects/TASKS.md'), 'utf-8')).toBe('# Tasks\n');
  });

  test('reports old commands in files the operator owns, not URLs, home paths or symlinked installs', () => {
    const home = makeHome({
      '.claude/skills/digest/SKILL.md': 'Run /agent-kevin:morning-briefing first, then $weekly-goals.\n',
      '.claude/commands/pulse.md': 'Notes live in ~/quick-pulse, not a command.\n',
      'AGENTS.md': 'SerpAPI lives at https://serpapi.com and the file seed-export.md is fine.\n'
    });
    symlinkSync(join(home, 'gone'), join(home, '.claude', 'skills', 'dangling'));
    expect(run(home)).toMatchObject({
      tasks: 'absent',
      mentions: [
        { file: join('.claude', 'skills', 'digest', 'SKILL.md'), commands: ['morning-briefing', 'weekly-goals'] }
      ]
    });
  });
});
