#!/usr/bin/env bun
/**
 * Upgrade migration for v0.6.0 — the home focus page moves into the dashboard, and
 * standup and where-am-i become focus playbooks.
 *
 * Before: `focus_write` rendered `<HOME>/focus.html` for all work. After: the
 * dashboard's Today → Focus tab is that view, and only projects keep a focus
 * page. The old page is generated output, so it is removed, but only when it
 * carries the `focus-data` block every generated page embeds; a hand-made file
 * at the same path is left alone and reported. The two retired skills' grants are
 * dropped from `.claude/settings.json`, since the upgrade's settings merge only adds.
 *
 * Run by `/agent-kevin:upgrade` via `run_upgrade` (outside the Bash sandbox).
 * Idempotent. Contract: prints a single-line JSON report as its LAST stdout
 * line; exits non-zero on failure.
 */
import { existsSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

const VERSION = '0.6.0';
const first = (...values: (string | undefined)[]): string | undefined =>
  values.map((value) => value?.trim()).find((value) => value);

const HOME = resolve(first(process.env.KEVIN_HOME, process.env.AGENT_HOME) ?? process.cwd());
const FOCUS_PAGE = resolve(HOME, 'focus.html');
const FOCUS_DATA = /<script\s+type="application\/json"\s+id="focus-data"\s*>/;
const SETTINGS = resolve(HOME, '.claude', 'settings.json');
const DEAD_GRANTS = ['Skill(agent-kevin:standup)', 'Skill(agent-kevin:where-am-i)'];

type Action = 'removed' | 'kept-hand-made' | 'absent';

interface Report {
  ok: true;
  version: string;
  action: Action;
  grantsDropped: string[];
  notes: string[];
}

const isRecord = (value: unknown): value is Record<string, unknown> =>
  typeof value === 'object' && value !== null && !Array.isArray(value);

const retireFocusPage = (): Pick<Report, 'action' | 'notes'> => {
  if (!existsSync(FOCUS_PAGE)) {
    return { action: 'absent', notes: [] };
  }
  if (!FOCUS_DATA.test(readFileSync(FOCUS_PAGE, 'utf-8'))) {
    return {
      action: 'kept-hand-made',
      notes: [
        'focus.html has no focus-data block, so it was not generated by focus_write and was left in place. The home focus view now lives in the dashboard (Today → Focus).'
      ]
    };
  }
  rmSync(FOCUS_PAGE);
  return {
    action: 'removed',
    notes: ['The home focus view now lives in the dashboard (Today → Focus); project focus pages are unchanged.']
  };
};

/** Drop exactly the retired skills' grants from `permissions.allow`; every other entry keeps its place. */
const dropDeadGrants = (): string[] => {
  if (!existsSync(SETTINGS)) {
    return [];
  }
  const settings: unknown = JSON.parse(readFileSync(SETTINGS, 'utf-8'));
  const permissions = isRecord(settings) ? settings.permissions : undefined;
  const allow = isRecord(permissions) ? permissions.allow : undefined;
  if (!isRecord(settings) || !isRecord(permissions) || !Array.isArray(allow)) {
    return [];
  }
  const dropped = allow.filter((entry): entry is string => DEAD_GRANTS.includes(entry));
  if (dropped.length) {
    writeFileSync(
      SETTINGS,
      `${JSON.stringify({ ...settings, permissions: { ...permissions, allow: allow.filter((entry) => !DEAD_GRANTS.includes(entry)) } }, null, 2)}\n`
    );
  }
  return dropped;
};

try {
  const page = retireFocusPage();
  const report: Report = { ok: true, version: VERSION, ...page, grantsDropped: dropDeadGrants() };
  process.stdout.write(JSON.stringify(report) + '\n');
} catch (err) {
  const message = err instanceof Error ? err.message : String(err);
  process.stdout.write(JSON.stringify({ ok: false, version: VERSION, error: message }) + '\n');
  process.exit(1);
}
